ALTER TABLE users ADD COLUMN IF NOT EXISTS vk_id VARCHAR(64);
ALTER TABLE users ADD COLUMN IF NOT EXISTS google_id VARCHAR(64);
ALTER TABLE users ADD COLUMN IF NOT EXISTS name VARCHAR(255);
CREATE UNIQUE INDEX IF NOT EXISTS users_vk_id_idx ON users(vk_id) WHERE vk_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS users_google_id_idx ON users(google_id) WHERE google_id IS NOT NULL;
